services: 
    api:
        build: .
        depends_on:
            - postgres
        ports:
            - 8081:8081
        environment:
            - database_username=postgres
            - database_password=123456
            - database_name=fastapi
            - database_hostname=postgres
            - database_port=5432
            - algorithm=HS256
            - secret_key=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
            - access_token_expire_minutes=30
        volumes:
            - ./:/usr/src/app/:ro
        command: uvicorn app.main:app --host 0.0.0.0 --port 8081 --reload
        
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "123456"
            POSTGRES_DB: "fastapi"
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data 
volumes:
    postgres_data: 

