services: 
    api:
        image: rzchpp210814/fastapi:latest
        depends_on:
            - postgres
        ports:
            - 80:8081
        environment:
            - database_username=${database_username}
            - database_password=${database_password}
            - database_name=${database_name}
            - database_hostname=${database_hostname}
            - database_port=${database_port}
            - algorithm=${algorithm}
            - secret_key=${secret_key}
            - access_token_expire_minutes=${access_token_expire_minutes}
        volumes:
            - ./:/usr/src/app/:ro
        #command: uvicorn app.main:app --host 0.0.0.0 --port 8081 --reload
        
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${database_username}
            POSTGRES_PASSWORD: ${database_password}
            POSTGRES_DB: ${database_name}
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data 
volumes:
    postgres_data: 

